### ISSUE TITLE
Generating a guest step is blocked

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/prestashop-shop-creator#12]
**Describe the bug and add screenshots**
When we try to generate the data, the creation of guests is blocked
![image](https://user-images.githubusercontent.com/16067358/191476146-86e74bc0-571e-414b-afdc-a4ec3724578a.png)

**Steps to reproduce**

1. git clone https://github.com/PrestaShop/prestashop-shop-creator.git
2. cd prestashop-shop-creator
3. composer install
4. Set number of guest > 0 for example 3
5. php app/console.php
6. See error

**Comment by mflasquin** [comment]
Hi @khouloudbelguith can you provide your config/config.yml ?
I can't reproduce the issue for the moment
Thanks

**Comment by khouloudbelguith** [comment]
Hi @mflasquin,

I still reproduce the same issue
I attached a screen record

https://user-images.githubusercontent.com/16067358/198002888-b60acf64-7dde-4495-869f-3785f2d6b134.mp4

My file config.yml
```yml
# This file is auto-generated during the composer install
parameters:
    shop_id: 1
    customers: 1
    manufacturers: 1
    suppliers: 1
    addresses: 1
    aliases: 1
    categories: 1
    warehouses: 1
    carriers: 1
    specific_prices: 1
    attribute_groups: 1
    products: 1
    attributes: 1
    carts: 1
    cart_rules: 1
    customizations: 1
    features: 1
    feature_values: 1
    orders: 1
    guests: 1
    order_histories: 1
    range_prices: 1
    range_weights: 1
    product_attributes: 1
    images: 1
    order_messages: 1
    deliveries: 1
    connections: 1
    product_suppliers: 1
    order_carriers: 1
    order_details: 1
    feature_products: 1
    stores: 1
    profiles: 1
    stock_availables: 1
    langs:
        - fr_FR
        - en_US
```

Thanks!
