### ISSUE TITLE
Error "You first need to define an entry before using a relation with supplier"

### ISSUE THREAD

**Issue by linuxatico** [PrestaShop/prestashop-shop-creator#4]
Hello, 
I get this message:

```
root@serverxxx:/var/www/performance-project/shop/prestashop-shop-creator# php -d memory_limit=1512M app/console.php 
Generating 25 carrier entities
Generating 87 category entities
Generating 22 manufacturer entities
Generating 0 supplier entities
Generating 2411 product entities
You first need to define an entry before using a relation with supplier
```

while generating sample data with the following input file:

```
parameters:
    shop_id: 1
    customers: 10
    manufacturers: 22
    suppliers: 0
    addresses: 10
    aliases: 2
    categories: 87
    warehouses: 0
    carriers: 25
    specific_prices: 8526
    attribute_groups: 1
    products: 2411
    attributes: 98
    carts: 1
    cart_rules: 1
    customizations: 0
    features: 0
    feature_values: 0
    orders: 10
    guests: 1
    order_histories: 2
    range_prices: 16
    range_weights: 7
    product_attributes: 9758
    images: 3 # each product has this count of images, be careful if you set an high product count
    order_messages: 10
    deliveries: 10
    connections: 100
    product_suppliers: 0
    order_carriers: 2
    order_details: 10
    feature_products: 5
    stores: 1
    profiles: 5
    stock_availables: 12172
    langs:
        - it_IT
```

I followed the steps stated at https://github.com/PrestaShop/performance-project/blob/master/shop/README.md, and I stopped ad the last of point 1, I changed the values according to what I have on a very similar Prestashop instance. 

After the error, the generated directory contains the following files:

```
root@serverxxx:/var/www/performance-project/shop/prestashop-shop-creator# tree generated_data/
generated_data/
├── data
│   ├── carrier.xml
│   ├── category.xml
│   ├── manufacturer.xml
│   └── supplier.xml
├── img
│   ├── c
│   │   ├── ab.jpg
│   │   ├── ad.jpg
│   │   ├── autem.jpg
│   │   ├── aut.jpg
│   │   ├── consequatur.jpg
│   │   ├── doloremque.jpg
│   │   ├── doloribus.jpg
│   │   ├── dolor.jpg
│   │   ├── ea.jpg
│   │   ├── enim.jpg
│   │   ├── esse.jpg
│   │   ├── est.jpg
│   │   ├── et.jpg
│   │   ├── eveniet.jpg
│   │   ├── iste.jpg
│   │   ├── itaque.jpg
│   │   ├── molestiae.jpg
│   │   ├── nostrum.jpg
│   │   ├── quia.jpg
│   │   ├── quis.jpg
│   │   ├── quo.jpg
│   │   ├── reprehenderit.jpg
│   │   ├── sapiente.jpg
│   │   ├── sint.jpg
│   │   ├── sunt.jpg
│   │   ├── tempore.jpg
│   │   ├── ut.jpg
│   │   ├── vel.jpg
│   │   ├── voluptate.jpg
│   │   └── voluptatem.jpg
│   └── m
│       ├── et et.jpg
│       ├── et soluta.jpg
│       ├── eum dolores.jpg
│       ├── odio ut.jpg
│       ├── quia quisquam.jpg
│       └── sequi omnis.jpg
└── langs
    └── it
        └── data
            ├── carrier.xml
            ├── category.xml
            ├── manufacturer.xml
            └── supplier.xml

7 directories, 44 files

```
How can I solve "You first need to define an entry before using a relation with supplier" ?
